version: '3'
services:
  # app:
  #   build:
  #     context: ./cash_machine
  #     dockerfile: Dockerfile
  #   image: grossbit_app
  #   restart: always
  #   ports:
  #     - "8000:8000"
  #   env_file:
  #     - docker.env
  #   depends_on:
  #     - db
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_grossbit:/var/lib/postgresql/data
volumes:
  db_grossbit:
